Swift test migration

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -16,6 +16,8 @@ jobs:
     if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
     name: ${{ github.workflow }}
     runs-on: macos-26
+    permissions:
+      checks: write
     env:
       scheme: Calendr
 
@@ -23,11 +25,13 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v6
 
-      - name: Build
-        run: |
-          xcodebuild build-for-testing -scheme "$scheme" \
-          COMPILER_INDEX_STORE_ENABLE=NO CODE_SIGNING_ALLOWED=NO
-
       - name: Test
         run: |
-          set -o pipefail && xcodebuild test-without-building -scheme "$scheme" | xcbeautify
+          set -o pipefail && swift test --xunit-output=./report.xml
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v6
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          check_name: 'Test Report'
+          report_paths: './report.xml'
